### ISSUE TITLE
koa-server to graphql-server (crud)

### ISSUE THREAD

**Issue by biantris** [biantris/koa-server#9]
- [x] build a graphql-server with CRUD
- [x] use relay

**Comment by biantris** [comment]
crud:

- [ ] CreateEventMutation
- [ ] UpdateEventMutation
- [ ] DeleteEventMutation

**Comment by daniloab** [comment]
ModelAction could be better to read 

```
EventCreateMutation
EventUpdateMutation
EventDeleteMutation
```
